version: 2
jobs:
  build:
    machine: true
      image: ubuntu-2004:202111-02
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
      CACHEVER: 3
      TERM: dumb
    branches:
      ignore:
        - gh-pages # list of branches to ignore
    steps:
      - run:
          name: Install OpenJDK 11
          command: |
            wget -qO - https://adoptium.jfrog.io/adoptium/api/gpg/key/public | sudo apt-key add -
            sudo add-apt-repository --yes https://adoptium.jfrog.io/adoptium/deb/
            sudo apt-get update && sudo apt-get install temurin-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/temurin-17-jdk-amd64/bin/javac
            java -version
      - checkout
      - type: shell
        name: "Write CACHEVER to file"
        command: echo "$CACHEVER" > ~/CACHEVER.txt
      - restore_cache:
          key: sc-gateway-{{ .Branch }}-{{ checksum "~/CACHEVER.txt" }}
      - run:
          name: "Download dependencies"
          command: |
            ./mvnw -s .settings.xml -U --fail-never dependency:go-offline || true
      - save_cache:
          key: sc-gateway-{{ .Branch }}-{{ checksum "~/CACHEVER.txt" }}
          paths:
            - ~/.m2
      - run:
          name: "Running build"
          command: ./mvnw -s .settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install -U -P sonar -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - run:
          name: "Aggregate test results"
          when: always
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/.*-reports/.*" -exec cp {} ~/junit/ \;
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ~/junit/
          destination: artifacts
      - store_test_results:
          path: ~/junit/
          destination: testartifacts